export const bibleBooks = [
  { name: 'उत्‍पत्ति', chapters: 50 },
  { name: 'प्रस्थान', chapters: 40 },
  { name: 'लेवी', chapters: 27 },
  { name: 'गन्ती', chapters: 36 },
  { name: 'व्यवस्था', chapters: 34 },
  { name: 'यहोशू', chapters: 24 },
  { name: 'न्यायकर्ता', chapters: 21 },
  { name: 'रूत', chapters: 4 },
  { name: '१ शमूएल', chapters: 31 },
  { name: '२ शमूएल', chapters: 24 },
  { name: '१ राजा', chapters: 22 },
  { name: '२ राजा', chapters: 25 },
  { name: '१ इतिहास', chapters: 29 },
  { name: '२ इतिहास', chapters: 36 },
  { name: 'एज्रा', chapters: 10 },
  { name: 'नहेम्या', chapters: 13 },
  { name: 'एस्तर', chapters: 10 },
  { name: 'अय्यूब', chapters: 42 },
  { name: 'भजनसंग्रह', chapters: 150 },
  { name: 'हितोपदेश', chapters: 31 },
  { name: 'उपदेशक', chapters: 12 },
  { name: 'श्रेष्‍ठगीत', chapters: 8 },
  { name: 'यशैया', chapters: 66 },
  { name: 'यर्मिया', chapters: 52 },
  { name: 'विलाप', chapters: 5 },
  { name: 'इजकिएल', chapters: 48 },
  { name: 'दानियल', chapters: 12 },
  { name: 'होशे', chapters: 14 },
  { name: 'योएल', chapters: 3 },
  { name: 'आमोस', chapters: 9 },
  { name: 'ओबदिया', chapters: 1 },
  { name: 'योना', chapters: 4 },
  { name: 'मीका', chapters: 7 },
  { name: 'नहूम', chapters: 3 },
  { name: 'हबकूक', chapters: 3 },
  { name: 'सपन्या', chapters: 3 },
  { name: 'हाग्गै', chapters: 2 },
  { name: 'जकरिया', chapters: 14 },
  { name: 'मलाकी', chapters: 4 },
  { name: 'मत्ती', chapters: 28 },
  { name: 'मर्कूस', chapters: 16 },
  { name: 'लूका', chapters: 24 },
  { name: 'यूहन्ना', chapters: 21 },
  { name: 'प्रेरित', chapters: 28 },
  { name: 'रोमी', chapters: 16 },
  { name: '१ कोरिन्थी', chapters: 16 },
  { name: '२ कोरिन्थी', chapters: 13 },
  { name: 'गलाती', chapters: 6 },
  { name: 'एफिसी', chapters: 6 },
  { name: 'फिलिप्पी', chapters: 4 },
  { name: 'कलस्सी', chapters: 4 },
  { name: '१ थिस्सलोनिकी', chapters: 5 },
  { name: '२ थिस्सलोनिकी', chapters: 3 },
  { name: '१ तिमोथी', chapters: 6 },
  { name: '२ तिमोथी', chapters: 4 },
  { name: 'तीतस', chapters: 3 },
  { name: 'फिलेमोन', chapters: 1 },
  { name: 'हिब्रू', chapters: 13 },
  { name: 'याकूब', chapters: 5 },
  { name: '१ पत्रुस', chapters: 5 },
  { name: '२ पत्रुस', chapters: 3 },
  { name: '१ यूहन्ना', chapters: 5 },
  { name: '२ यूहन्ना', chapters: 1 },
  { name: '३ यूहन्ना', chapters: 1 },
  { name: 'यहूदा', chapters: 1 },
  { name: 'प्रकाश', chapters: 22 }
]
