name: Publish Tauri Release
on:
  push:
    branches: [release]
permissions:
  contents: write
jobs:
  publish:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build and publish Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v{{ env.APP_VERSION }}
          releaseName: "NCA2 v{{ env.APP_VERSION }}"
          releaseBody: "Release notes for v{{ env.APP_VERSION }}"
      - name: Generate latest.json
        run: |
          echo '{
            "version": "v${{ env.APP_VERSION }}",
            "notes": "Release notes for v${{ env.APP_VERSION }}",
            "pub_date": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'",
            "platforms": {
              "darwin-x86_64": {
                "url": "https://github.com/Saral33/NCA2/releases/download/v${{ env.APP_VERSION }}/app-x86_64.app.tar.gz",
                "signature": "'$(cat target/release/app-x86_64.app.tar.gz.sig || echo '')'"
              },
              "darwin-aarch64": {
                "url": "https://github.com/Saral33/NCA2/releases/download/v${{ env.APP_VERSION }}/app-aarch64.app.tar.gz",
                "signature": "'$(cat target/release/app-aarch64.app.tar.gz.sig || echo '')'"
              },
              "linux-x86_64": {
                "url": "https://github.com/Saral33/NCA2/releases/download/v${{ env.APP_VERSION }}/app-amd64.AppImage.tar.gz",
                "signature": "'$(cat target/release/app-amd64.AppImage.tar.gz.sig || echo '')'"
              },
              "windows-x86_64": {
                "url": "https://github.com/Saral33/NCA2/releases/download/v${{ env.APP_VERSION }}/app-x64.msi.zip",
                "signature": "'$(cat target/release/app-x64.msi.sig || echo '')'"
              }
            }
          }' > latest.json
      - name: Upload latest.json to Release
        uses: softprops/action-gh-release@v1
        with:
          files: latest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}